# Generated by Django 5.2.11 on 2026-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Name')),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('stack', models.IntegerField()),
            ],
        ),
    ]
